<a href="https://colab.research.google.com/github/NayanaMarques/ANN_2021/blob/master/Classification_ANN/ANN_faulty_diagnosis_catalysis_may_26_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
# objetivo: entrar com os dados de temperatura, pressão e vazão para verificar se haverá falha
# bibliotecas usadas
import numpy as np
import pandas as pd
from sklearn import  preprocessing # escalonar
from sklearn.neural_network import MLPClassifier # rede neural classificação
from sklearn.metrics import confusion_matrix # nao foi utilizado

In [34]:
!git clone https://github.com/ucfilho/ANN_2021_01
%cd ANN_2021_01

Cloning into 'ANN_2021_01'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (291/291), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 291 (delta 164), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (291/291), 292.18 KiB | 4.36 MiB/s, done.
Resolving deltas: 100% (164/164), done.
/content/ANN_2021_01/ANN_2021_01/ANN_2021_01


In [35]:
# temperatura / pressão / vazão / fallhas: Y1 - Y2 - Y3 (0 - 0 - 0 --> sem falha)
df=pd.read_csv("FAULT_DIAGNOSIS_maio_25_2017.txt",sep='\t')
print(df.head())

    TF    P  Flow  Y1  Y2  Y3
0  400  100   200   0   0   0
1  420  100   200   0   0   0
2  380  100   200   0   0   0
3  400  100   200   0   0   0
4  400   90   200   0   0   0


In [36]:
# separa os dados em normatizados e originais
X = df[['TF','P','Flow']]


In [37]:
y = df[['Y1','Y2','Y3']]
print(y)

    Y1  Y2  Y3
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
5    0   0   0
6    0   0   0
7    1   0   0
8    1   0   0
9    1   0   0
10   1   0   0
11   1   0   0
12   0   1   0
13   0   1   0
14   0   0   1
15   0   0   1


In [38]:
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.10, shuffle=True, random_state=3)

In [39]:
scaler_X = preprocessing.MinMaxScaler((-1,1)).fit(X)
# scaler_Y = preprocessing.MinMaxScaler((-1,1)).fit(y)

In [40]:
# nao foi utilizado test pois são poucos dados
X_train = X.copy()
y_train = y.copy()
X_train = scaler_X.transform(X_train)
#y_train = scaler_Y.transform(y_train)

In [41]:
'''
X_train = scaler_X.transform(X_train)
X_test = scaler_X.transform(X_test)
y_train = scaler_Y.transform(y_train)
y_test = scaler_Y.transform(y_test)
'''

'\nX_train = scaler_X.transform(X_train)\nX_test = scaler_X.transform(X_test)\ny_train = scaler_Y.transform(y_train)\ny_test = scaler_Y.transform(y_test)\n'

In [42]:
# define a rede neural 
model = MLPClassifier(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(15),
                     random_state=1)

In [43]:
# treina a rede neural
model.fit(X_train, y_train)

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=15, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [44]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=model.predict(X_train)
# y_calc_test=model.predict(X_test)

In [45]:
y_train

Y1  Y2  Y3
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
5    0   0   0
6    0   0   0
7    1   0   0
8    1   0   0
9    1   0   0
10   1   0   0
11   1   0   0
12   0   1   0
13   0   1   0
14   0   0   1
15   0   0   1

In [46]:
y_calc_train

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [47]:
X_train

array([[-0.2       ,  1.        , -0.42857143],
       [-0.04      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -0.42857143],
       [-0.2       ,  1.        , -0.42857143],
       [-0.2       ,  0.        , -0.42857143],
       [-0.2       ,  1.        ,  0.14285714],
       [-0.2       ,  1.        , -1.        ],
       [-1.        ,  1.        , -0.42857143],
       [-0.8       ,  0.        , -0.42857143],
       [-0.6       , -1.        , -0.42857143],
       [-0.44      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -1.        ],
       [-0.2       ,  1.        ,  1.        ],
       [-0.2       ,  1.        ,  0.42857143],
       [ 1.        ,  1.        , -0.42857143],
       [ 0.8       ,  1.        , -1.        ]])

In [48]:
# considerando uma temperatura de 300, pressão de 90 e vazão de 300, qual resultado?
X_exemplo =pd.DataFrame({'TF':[300],'P':[90],'Flow':[300]}) 
# X_exemplo =pd.DataFrame({'TF':[400],'P':[100],'Flow':[200]})
X_exemplo =  scaler_X.transform(X_exemplo)
y_exemplo=model.predict(X_exemplo)
print(y_exemplo)

[[0 0 0]]
