<a href="https://colab.research.google.com/github/NayanaMarques/ANN_2021/blob/master/Classification_ANN/ANN_faulty_diagnosis_catalysis_one_class_may_26_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# bibliotecas usadas
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [22]:
!git clone https://github.com/ucfilho/ANN_2021_01
%cd ANN_2021_01

Cloning into 'ANN_2021_01'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (291/291), done.
remote: Compressing objects: 100% (277/277), done.
remote: Total 291 (delta 165), reused 15 (delta 8), pack-reused 0
Receiving objects: 100% (291/291), 290.12 KiB | 2.69 MiB/s, done.
Resolving deltas: 100% (165/165), done.
/content/ANN_2021_01/ANN_2021_01


In [23]:
df=pd.read_csv("FAULT_DIAGNOSIS_maio_25_2017.txt",sep='\t')
print(df.head())

    TF    P  Flow  Y1  Y2  Y3
0  400  100   200   0   0   0
1  420  100   200   0   0   0
2  380  100   200   0   0   0
3  400  100   200   0   0   0
4  400   90   200   0   0   0


In [24]:
# separa os dados em normatizados e originais
X = df[['TF','P','Flow']]


In [25]:
y = df[['Y1','Y2','Y3']]
print(y)

    Y1  Y2  Y3
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
5    0   0   0
6    0   0   0
7    1   0   0
8    1   0   0
9    1   0   0
10   1   0   0
11   1   0   0
12   0   1   0
13   0   1   0
14   0   0   1
15   0   0   1


In [26]:
yy = np.array(y) # transformando dataframe em array
y_one = [] # lista em branco
for yi in yy: # nao aplicavel caso tenha 2 erros ao mesmo tempo
  y1,y2,y3 = yi
  if(y1 == 1): # se y1 = 1
    y_one.append(1) #append - armazenar o valor em y_one
  elif(y2 == 1): # elif y1 diferente de 1 e y2 =1
    y_one.append(2)
  elif(y3 == 1): # elif y1 diferente de 1, y2 diferente de 1 e y3 =1
    y_one.append(3)
  else: # nenhum igual a 1 (o que sobrou)
    y_one.append(0)

In [27]:
yy

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [28]:
y_one # qual erro para cada caso? 0 - sem erro, ou erro 1, 2 ou 3

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3]

In [29]:
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.10, shuffle=True, random_state=3)
# nao foram utilizados dados para teste pois são poucos dados

In [30]:
scaler_X = preprocessing.MinMaxScaler((-1,1)).fit(X)
# scaler_Y = preprocessing.MinMaxScaler((-1,1)).fit(y)

In [31]:
X_train = X.copy()
y_train = y_one.copy()
X_train = scaler_X.transform(X_train)
#y_train = scaler_Y.transform(y_train)

In [32]:
'''
X_train = scaler_X.transform(X_train)
X_test = scaler_X.transform(X_test)
y_train = scaler_Y.transform(y_train)
y_test = scaler_Y.transform(y_test)
'''

'\nX_train = scaler_X.transform(X_train)\nX_test = scaler_X.transform(X_test)\ny_train = scaler_Y.transform(y_train)\ny_test = scaler_Y.transform(y_test)\n'

In [33]:
# define a rede neural 
model = MLPClassifier(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(15),
                     random_state=1)

In [34]:
# treina a rede neural
model.fit(X_train, y_train)

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=15, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [35]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=model.predict(X_train)
# y_calc_test=model.predict(X_test)

In [36]:
y_train

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3]

In [37]:
y_calc_train

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3])

In [38]:
X_train

array([[-0.2       ,  1.        , -0.42857143],
       [-0.04      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -0.42857143],
       [-0.2       ,  1.        , -0.42857143],
       [-0.2       ,  0.        , -0.42857143],
       [-0.2       ,  1.        ,  0.14285714],
       [-0.2       ,  1.        , -1.        ],
       [-1.        ,  1.        , -0.42857143],
       [-0.8       ,  0.        , -0.42857143],
       [-0.6       , -1.        , -0.42857143],
       [-0.44      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -1.        ],
       [-0.2       ,  1.        ,  1.        ],
       [-0.2       ,  1.        ,  0.42857143],
       [ 1.        ,  1.        , -0.42857143],
       [ 0.8       ,  1.        , -1.        ]])

In [39]:
X_exemplo =pd.DataFrame({'TF':[300],'P':[90],'Flow':[300]})
# X_exemplo =pd.DataFrame({'TF':[400],'P':[100],'Flow':[200]})
X_exemplo =  scaler_X.transform(X_exemplo)
y_exemplo=model.predict(X_exemplo)
print(y_exemplo)

[1]


In [40]:
df = pd.DataFrame({'true':y_train,'calc':y_calc_train})
df = pd.crosstab(df['true'],df['calc'])

In [41]:
df

calc  0  1  2  3
true            
0     7  0  0  0
1     0  5  0  0
2     0  0  2  0
3     0  0  0  2