<a href="https://colab.research.google.com/github/NayanaMarques/ANN_2021/blob/master/Classification_ANN/SVM_faulty_diagnosis_catalysis_one_class_may_26_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Maquina de vetor suporte - não é rede neural, mas pode ser usado como
# bibliotecas usadas
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.svm import SVC # SVC - classifier / SVR - regression
from sklearn.metrics import confusion_matrix

In [2]:
!git clone https://github.com/ucfilho/ANN_2021_01
%cd ANN_2021_01

Cloning into 'ANN_2021_01'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (291/291), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 291 (delta 164), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (291/291), 292.18 KiB | 5.96 MiB/s, done.
Resolving deltas: 100% (164/164), done.
/content/ANN_2021_01


In [3]:
df=pd.read_csv("FAULT_DIAGNOSIS_maio_25_2017.txt",sep='\t')
print(df.head())

    TF    P  Flow  Y1  Y2  Y3
0  400  100   200   0   0   0
1  420  100   200   0   0   0
2  380  100   200   0   0   0
3  400  100   200   0   0   0
4  400   90   200   0   0   0


In [4]:
# separa os dados em normatizados e originais
X = df[['TF','P','Flow']]


In [5]:
y = df[['Y1','Y2','Y3']]
print(y)

    Y1  Y2  Y3
0    0   0   0
1    0   0   0
2    0   0   0
3    0   0   0
4    0   0   0
5    0   0   0
6    0   0   0
7    1   0   0
8    1   0   0
9    1   0   0
10   1   0   0
11   1   0   0
12   0   1   0
13   0   1   0
14   0   0   1
15   0   0   1


In [6]:
yy = np.array(y)
y_one = []
for yi in yy:
  y1,y2,y3 = yi
  if(y1 == 1):
    y_one.append(1)
  elif(y2 ==1):
    y_one.append(2)
  elif(y3 ==1):
    y_one.append(3)
  else:
    y_one.append(0)


  

In [7]:
yy

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [8]:
y_one

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3]

In [9]:
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.10, shuffle=True, random_state=3)

In [10]:
scaler_X = preprocessing.MinMaxScaler((-1,1)).fit(X)
# scaler_Y = preprocessing.MinMaxScaler((-1,1)).fit(y)

In [11]:
X_train = X.copy()
y_train = y_one.copy()
X_train = scaler_X.transform(X_train)
#y_train = scaler_Y.transform(y_train)

In [12]:
'''
X_train = scaler_X.transform(X_train)
X_test = scaler_X.transform(X_test)
y_train = scaler_Y.transform(y_train)
y_test = scaler_Y.transform(y_test)
'''

'\nX_train = scaler_X.transform(X_train)\nX_test = scaler_X.transform(X_test)\ny_train = scaler_Y.transform(y_train)\ny_test = scaler_Y.transform(y_test)\n'

In [13]:
# define support vector machine
model = SVC()

In [14]:
# treina a rede neural
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=model.predict(X_train)
# y_calc_test=model.predict(X_test)

In [16]:
y_train

[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3]

In [17]:
y_calc_train

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 2, 3, 3])

In [18]:
X_train

array([[-0.2       ,  1.        , -0.42857143],
       [-0.04      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -0.42857143],
       [-0.2       ,  1.        , -0.42857143],
       [-0.2       ,  0.        , -0.42857143],
       [-0.2       ,  1.        ,  0.14285714],
       [-0.2       ,  1.        , -1.        ],
       [-1.        ,  1.        , -0.42857143],
       [-0.8       ,  0.        , -0.42857143],
       [-0.6       , -1.        , -0.42857143],
       [-0.44      ,  1.        , -0.42857143],
       [-0.36      ,  1.        , -1.        ],
       [-0.2       ,  1.        ,  1.        ],
       [-0.2       ,  1.        ,  0.42857143],
       [ 1.        ,  1.        , -0.42857143],
       [ 0.8       ,  1.        , -1.        ]])

In [19]:
X_exemplo =pd.DataFrame({'TF':[300],'P':[90],'Flow':[300]})
# X_exemplo =pd.DataFrame({'TF':[400],'P':[100],'Flow':[200]})
X_exemplo =  scaler_X.transform(X_exemplo)
y_exemplo=model.predict(X_exemplo)
print(y_exemplo)

[1]


In [20]:
df = pd.DataFrame({'true':y_train,'calc':y_calc_train})
df = pd.crosstab(df['true'],df['calc'])

In [21]:
df

calc  0  1  2  3
true            
0     7  0  0  0
1     2  3  0  0
2     0  0  2  0
3     0  0  0  2